In [16]:
f = open("./test.txt", "w")
for i in range(3):
  name = input("이름을 입력하세요: ")
  pw = input("비밀번호를 입력하세요: ")
  f.write(f"이름 : {name}, 비밀번호 : {pw}\n")
f.close()
f2 = open("./test.txt")
print(f2.read())
f2.close()

이름을 입력하세요: a1
비밀번호를 입력하세요: aaa
이름을 입력하세요: b1
비밀번호를 입력하세요: bbb
이름을 입력하세요: c1
비밀번호를 입력하세요: ccc
이름 : a1, 비밀번호 : aaa
이름 : b1, 비밀번호 : bbb
이름 : c1, 비밀번호 : ccc



In [73]:
while(1):
  box = []
  tel_name_list = []
  name = input("이름을 입력하세요: ")
  pw = input("비밀번호를 입력하세요: ")
  f3 = open("./test.txt")
  name_list = f3.readlines()
  check = "이름 : " + name + ", 비밀번호 : " + pw + "\n"
  if check in name_list:
      print("로그인 성공")
      ff = open("./member_tel.txt")
      num_list = ff.readlines()
      for i in num_list:
        box.append(i.split(" "))
      for i in range(len(box)):
        tel_name_list.append(box[i][0])
      if name in tel_name_list:
          idx = tel_name_list.index(name)
          number = input("수정할 전화번호를 입력하세요: ")
          num_list[idx] = name +" " + number + "\n"
      else:
        number = input("전화번호를 입력하세요: ")
        num_list.append(name +" " + number + "\n")
      ff = open("./member_tel.txt", "w")
      ff.writelines(num_list)
      ff.close()
  else:
      print("로그인 실패")
f3.close()

KeyboardInterrupt: ignored

In [75]:
while(1):
  try:
    num = int(input("숫자 입력:"))
  except:
    print("정수가 아님! 정수를 입력해주세요!")
  else:
    print(f"정수 입력 성공: {num}")
    break

숫자 입력:20.5
정수가 아님! 정수를 입력해주세요!
숫자 입력:가
정수가 아님! 정수를 입력해주세요!
숫자 입력:10
정수 입력 성공: 10


In [77]:
import numpy as np
x = np.array([3, 1, 2])
print(x)
type(x)

[3 1 2]


numpy.ndarray

In [91]:
import numpy as np
array = np.zeros(10)
print(array)
array[4] = 1
print(array)
array = np.arange(10,30)
print(array)
array = np.random.randint(0,100,size = (2,2))
print(array)
array = np.random.rand(2,4)
print(array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[73 58]
 [85 30]]
[[0.54658639 0.10677707 0.30567028 0.37693226]
 [0.66599983 0.85076466 0.7160951  0.33565009]]


In [209]:
a = np.arange(35,75)
a = a.reshape(-1,4)
print(a)
print(a[::-1])
print(a[1:-1], a[2::])

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
[[39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]] [[43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]


reshape와 resize의 차이점
reshape는
return값 있음, 원래 행렬 유지
( , ) 행과 열 중 하나를 -1로 하면 자동으로 맞춰줌
resize는 return값 없음, 원래 행렬 유지X
정해진 크기보다 적은 수를 넣으면 나머지는 0으로 채움, 많은 수를 넣으면 알아서 잘라줌


In [197]:
result = []
print(a[:,-1])
print(a[:,-1].reshape(10,1))
b = a[:,-1].reshape(10,1)
print(b[::-1])
array = np.random.randint(0,50, size = (5,6))
print(array)
for i in array:
  for j in i:
    if j % 2 == 0:
      result.append(j)
array = np.array(result)
print("짝수만 출력 :",array) # print("짝수만 출력 :",array[array % 2 == 0]) 로 하면 간편
print(array.shape)
array.size

[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
[[31 48  1 21 49 47]
 [15 44  1 28 23 36]
 [ 0  7 28 18 13  3]
 [32  2 47 17 21  2]
 [12 32 32 23  2  3]]
짝수만 출력 : [48 44 28 36  0 28 18 32  2  2 12 32 32  2]
(14,)


14